/**
 * HENU VOUCHER OCR — MASTER CANONICAL SCHEMA
 * Module: Henu Voucher OCR
 * 
 * Single source of truth for:
 * - Extraction mapping
 * - Normalization
 * - Validation rules
 * - Review UI
 * - Excel XLSX generation
 */

import { HenuVoucherData, VoucherFieldMetadata, ExtractedVoucherFields, ExtractedFieldResult } from './types';

export const HENU_VOUCHER_FIELDS: VoucherFieldMetadata[] = [
  // ── 1. Society Name (TEXT) ──
  {
    key: 'society_name',
    label: 'Society Name',
    category: 'header',
    semanticType: 'TEXT',
    dataType: 'string',
    extractionType: 'name',
    required: true,
    description: 'Name of the Co-operative Housing Society',
    excelColumn: 'Society Name',
    excelWidth: 32,
    format: 'text',
    likelyLabels: ['Society Name', 'Society', 'Co-operative Housing Society', 'Co-op Housing Society', 'Co-op Society', 'CHS Ltd', 'सोसायटी'],
    likelyLocation: 'Header region (top 0-10%)',
    extractionStrategy: 'Header layout extraction + targeted crop',
    ocrEnginePreference: 'glm',
    validationStrategy: 'Mandatory non-empty text without voucher metadata contamination',
    normalizationStrategy: 'Clean whitespace, preserve verbatim case & punctuation',
    confidenceStrategy: 'High weight on society keywords and upper document placement',
  },
  // ── 2. Registration Number (IDENTIFIER) ──
  {
    key: 'registration_no',
    label: 'Registration Number',
    category: 'header',
    semanticType: 'IDENTIFIER',
    dataType: 'string',
    extractionType: 'mixed_alphanumeric',
    description: 'Society Registration/Approval Number',
    excelColumn: 'Registration No',
    excelWidth: 26,
    format: 'text',
    likelyLabels: ['Registration Number', 'Registration No', 'Reg No', 'Reg. No', 'Regn No', 'Regn. No', 'Year', 'नोंदणी क्र.'],
    likelyLocation: 'Header subtitle region (top 7-13%)',
    extractionStrategy: 'Mixed alphanumeric pattern matcher + targeted crop',
    ocrEnginePreference: 'glm',
    validationStrategy: 'Validates presence of alphanumeric registration code',
    normalizationStrategy: 'Preserve slashes, hyphens, and numeric chunks',
    confidenceStrategy: 'Verified against registration patterns (e.g. BOM/MUM/PUN)',
  },
  // ── 3. Society Address (TEXT) ──
  {
    key: 'society_address',
    label: 'Society Address',
    category: 'header',
    semanticType: 'TEXT',
    dataType: 'string',
    extractionType: 'address',
    description: 'Physical registered location or address of society',
    excelColumn: 'Society Address',
    excelWidth: 36,
    format: 'text',
    likelyLabels: ['Address', 'Road', 'Marg', 'Nagar', 'Street', 'Mumbai', 'Pune', 'Thane', 'रस्ता'],
    likelyLocation: 'Header sub-block (top 12-18%)',
    extractionStrategy: 'Address entity recognition + spatial line aggregation',
    ocrEnginePreference: 'glm',
    validationStrategy: 'Text containing pin code or road/area keywords',
    normalizationStrategy: 'Preserve comma-delimited street/city tokens',
    confidenceStrategy: 'Matched against geographic and postal identifiers',
  },
  // ── 4. Voucher Number (IDENTIFIER) ──
  {
    key: 'voucher_no',
    label: 'Voucher Number',
    category: 'voucher_info',
    semanticType: 'IDENTIFIER',
    dataType: 'string',
    extractionType: 'reference_number',
    required: true,
    description: 'Sequential or alphanumeric voucher document number',
    excelColumn: 'Voucher No',
    excelWidth: 16,
    format: 'text',
    likelyLabels: ['Voucher Number', 'Voucher No', 'Voucher No.', 'V.No.', 'V.No', 'Vch No', 'VR No', 'Voucher #', 'No.', 'पावती क्र.'],
    likelyLocation: 'Top right box (0-10% height, 70-100% width)',
    extractionStrategy: 'Anchor-adjacent identifier extraction + isolated crop',
    ocrEnginePreference: 'consensus',
    validationStrategy: 'Mandatory alphanumeric/numeric identifier, non-empty',
    normalizationStrategy: 'Strip label prefix, trim whitespace, reject non-digit noise words',
    confidenceStrategy: 'Evidence proximity to Voucher No label box',
  },
  // ── 5. Voucher Date (DATE) ──
  {
    key: 'voucher_date',
    label: 'Voucher Date',
    category: 'voucher_info',
    semanticType: 'DATE',
    dataType: 'date',
    extractionType: 'date',
    required: true,
    description: 'Transaction date (DDMMYYYY canonical format)',
    excelColumn: 'Voucher Date',
    excelWidth: 15,
    format: 'date',
    likelyLabels: ['Voucher Date', 'Date', 'Date:', 'Dated', 'Dt', 'Dt.', 'दिनांक'],
    likelyLocation: 'Top right date box (8-18% height, 70-100% width)',
    extractionStrategy: 'Date parser with multi-format support (slash, dot, hyphen, textual month)',
    ocrEnginePreference: 'consensus',
    validationStrategy: 'Strict 8-digit DDMMYYYY calendar validity (1970-2099)',
    normalizationStrategy: 'Normalize all dates into strictly formatted DDMMYYYY',
    confidenceStrategy: 'Highest confidence when parsed calendar date matches valid DDMMYYYY',
  },
  // ── 6. Pay To (Payee) (TEXT) ──
  {
    key: 'pay_to',
    label: 'Pay To (Payee)',
    category: 'parties',
    semanticType: 'TEXT',
    dataType: 'string',
    extractionType: 'name',
    required: true,
    description: 'Party, vendor, contractor, or person paid',
    excelColumn: 'Pay To',
    excelWidth: 28,
    format: 'text',
    likelyLabels: ['Pay To', 'Payee', 'Paid To', 'Name', 'M/s', 'Mr', 'Mrs', 'Shri', 'श्री', 'नाव'],
    likelyLocation: 'Upper-left party row (18-28% height, 10-60% width)',
    extractionStrategy: 'Anchor right/down text search + handwriting crop consensus',
    ocrEnginePreference: 'consensus',
    validationStrategy: 'Mandatory party name text, strict verbatim English/regional transcription',
    normalizationStrategy: 'Strip label prefixes, retain vendor/person title',
    confidenceStrategy: 'Multi-engine consensus between GLM, FireRed, and Kraken',
  },
  // ── 7. Charge To (Ledger Head) (TEXT) ──
  {
    key: 'charge_to',
    label: 'Charge To (Ledger Head)',
    category: 'parties',
    semanticType: 'TEXT',
    dataType: 'string',
    extractionType: 'ledger_text',
    description: 'Accounting debit ledger head / expense category',
    excelColumn: 'Charge To',
    excelWidth: 26,
    format: 'text',
    likelyLabels: ['Charge To', 'Ledger Head', 'Debit To', 'Account', 'A/C', 'A/c Head', 'खाते', 'खर्च'],
    likelyLocation: 'Upper-right party row (18-28% height, 65-100% width)',
    extractionStrategy: 'Spatial anchor extraction + ledger head classification',
    ocrEnginePreference: 'consensus',
    validationStrategy: 'Accounting expense ledger head text',
    normalizationStrategy: 'Standardize A/C suffixes, preserve uppercase ledger head names',
    confidenceStrategy: 'Anchor match to CHARGE TO / DEBIT TO box',
  },
  // ── 8. Particulars / Narration (TEXT) ──
  {
    key: 'particulars',
    label: 'Particulars / Narration',
    category: 'particulars',
    semanticType: 'TEXT',
    dataType: 'string',
    extractionType: 'sentence',
    description: 'Transaction narration and purpose of payment',
    excelColumn: 'Particulars',
    excelWidth: 38,
    format: 'text',
    likelyLabels: ['Particulars', 'Narration', 'Description', 'Being', 'For', 'तपशील', 'बद्दल'],
    likelyLocation: 'Mid-body left section (28-60% height, 0-60% width)',
    extractionStrategy: 'Multi-line block accumulator preserving row boundaries',
    ocrEnginePreference: 'consensus',
    validationStrategy: 'Verbatim narrative transcription without paraphrasing or translating',
    normalizationStrategy: 'Preserve internal linebreaks, strip bounding box borders',
    confidenceStrategy: 'High confidence on structured narrative blocks',
  },
  // ── 9. Bill Number (IDENTIFIER) ──
  {
    key: 'bill_no',
    label: 'Bill Number',
    category: 'payment_details',
    semanticType: 'IDENTIFIER',
    dataType: 'string',
    extractionType: 'reference_number',
    description: 'Vendor invoice or bill identifier',
    excelColumn: 'Bill No',
    excelWidth: 18,
    format: 'text',
    likelyLabels: ['Bill Number', 'Bill No', 'Bill No.', 'Invoice Number', 'Invoice No', 'Inv No', 'बिल नं'],
    likelyLocation: 'Lower-left payment grid (58-66% height, 10-60% width)',
    extractionStrategy: 'Anchor value scan + targeted crop',
    ocrEnginePreference: 'consensus',
    validationStrategy: 'Alphanumeric bill/invoice reference string',
    normalizationStrategy: 'Clean punctuation, remove non-identifier noise',
    confidenceStrategy: 'Spatial proximity to Bill No label',
  },
  // ── 10. Bank Name (TEXT) ──
  {
    key: 'bank_name',
    label: 'Bank Name',
    category: 'payment_details',
    semanticType: 'TEXT',
    dataType: 'string',
    extractionType: 'name',
    description: 'Bank from which payment was drawn',
    excelColumn: 'Bank Name',
    excelWidth: 24,
    format: 'text',
    likelyLabels: ['Bank Name', 'Bank', 'A/C with', 'Drawn On', 'HDFC', 'SBI', 'ICICI', 'AXIS', 'SARASWAT', 'बँक'],
    likelyLocation: 'Lower-left payment grid (65-72% height, 15-60% width)',
    extractionStrategy: 'Known bank dictionary lookup + anchor search',
    ocrEnginePreference: 'consensus',
    validationStrategy: 'Valid bank entity name',
    normalizationStrategy: 'Clean trailing punctuation and lines',
    confidenceStrategy: 'Matches known banking institutions',
  },
  // ── 11. Cheque Number (IDENTIFIER) ──
  {
    key: 'cheque_no',
    label: 'Cheque / Ref Number',
    category: 'payment_details',
    semanticType: 'IDENTIFIER',
    dataType: 'string',
    extractionType: 'reference_number',
    description: 'Cheque number, UTR reference, or transaction ID',
    excelColumn: 'Cheque No',
    excelWidth: 18,
    format: 'text',
    likelyLabels: ['Cheque Number', 'Cheque No', 'Cheque No.', 'Chq No', 'Ch. No', 'Reference No', 'Ref No', 'UTR', 'NEFT', 'चेक नं'],
    likelyLocation: 'Lower-left payment grid (71-78% height, 15-40% width)',
    extractionStrategy: 'Strict numeric/alphanumeric reference parser with false-positive dictionary rejection',
    ocrEnginePreference: 'consensus',
    validationStrategy: 'Rejects invalid noise words like "ATE", "DATE", "CHQ", "NO"',
    normalizationStrategy: 'Filter non-digit English words, keep numeric/UTR tokens',
    confidenceStrategy: 'High confidence on 6-digit cheque numbers or UTR strings',
  },
  // ── 12. Cheque Date (DATE) ──
  {
    key: 'cheque_date',
    label: 'Cheque Date',
    category: 'payment_details',
    semanticType: 'DATE',
    dataType: 'date',
    extractionType: 'date',
    description: 'Date written on cheque (DDMMYYYY canonical format)',
    excelColumn: 'Cheque Date',
    excelWidth: 15,
    format: 'date',
    likelyLabels: ['Cheque Date', 'Chq Date', 'Date', 'Dt', 'Dated', 'दिनांक'],
    likelyLocation: 'Lower-left payment grid adjacent to cheque no (71-78% height, 40-60% width)',
    extractionStrategy: 'Spatial anchor extraction next to Cheque No',
    ocrEnginePreference: 'consensus',
    validationStrategy: 'Valid 8-digit DDMMYYYY calendar date',
    normalizationStrategy: 'Normalize to DDMMYYYY format',
    confidenceStrategy: 'Calendar format validation',
  },
  // ── 13. Rupees (Words or Net Rs.) (TEXT) ──
  {
    key: 'rupees',
    label: 'Rupees (Words / Net Rs.)',
    category: 'net',
    semanticType: 'TEXT',
    dataType: 'string',
    extractionType: 'words',
    description: 'Amount in words or net highlighted rupee text',
    excelColumn: 'Rupees',
    excelWidth: 28,
    format: 'text',
    likelyLabels: ['Rupees', 'Rupees in Words', 'Amount in Words', 'Rs.', '₹', 'रुपये'],
    likelyLocation: 'Lower-left payment grid (77-85% height, 5-60% width)',
    extractionStrategy: 'Currency narrative block parser + numeric correlation',
    ocrEnginePreference: 'consensus',
    validationStrategy: 'Word text cross-checked against numeric net_paid',
    normalizationStrategy: 'Trim whitespace, preserve currency verbal tokens (e.g. Only)',
    confidenceStrategy: 'Cross-validated against numeric net_paid amount',
  },
  // ── 14. Bill Amount 1 (MONEY) ──
  {
    key: 'bill_amount_1',
    label: 'Bill Amount 1',
    category: 'financials',
    semanticType: 'MONEY',
    dataType: 'number',
    extractionType: 'amount',
    description: 'Primary invoice / bill amount',
    excelColumn: 'Bill Amount 1',
    excelWidth: 16,
    format: 'currency',
    likelyLabels: ['Bill Amount 1', 'Bill Amount', 'Bill Amt', 'Gross Amount', 'Amount', 'रक्कम १'],
    likelyLocation: 'Financial table row 1 (30-38% height, 75-100% width)',
    extractionStrategy: 'Right column table row extractor + crop OCR',
    ocrEnginePreference: 'firered',
    validationStrategy: 'Strict monetary numeric decimal format',
    normalizationStrategy: 'Normalize currency symbols, commas, and trailing paise',
    confidenceStrategy: 'Table grid cell coordinate match',
  },
  // ── 15. Bill Amount 2 (MONEY) ──
  {
    key: 'bill_amount_2',
    label: 'Bill Amount 2',
    category: 'financials',
    semanticType: 'MONEY',
    dataType: 'number',
    extractionType: 'amount',
    description: 'Secondary invoice amount or supplementary cost',
    excelColumn: 'Bill Amount 2',
    excelWidth: 16,
    format: 'currency',
    likelyLabels: ['Bill Amount 2', 'Extra', 'Supplementary', 'रक्कम २'],
    likelyLocation: 'Financial table row 2 (38-44% height, 75-100% width)',
    extractionStrategy: 'Financial table row 2 targeted crop',
    ocrEnginePreference: 'firered',
    validationStrategy: 'Monetary numeric decimal format',
    normalizationStrategy: 'Clean numeric string to float',
    confidenceStrategy: 'Coordinates on row 2 right column',
  },
  // ── 16. Advance / Paid (MONEY) ──
  {
    key: 'advance_paid',
    label: 'Advance / Paid',
    category: 'financials',
    semanticType: 'MONEY',
    dataType: 'number',
    extractionType: 'amount',
    description: 'Advance amount previously paid or deducted',
    excelColumn: 'Advance / Paid',
    excelWidth: 16,
    format: 'currency',
    likelyLabels: ['Advance / Paid', 'Advance', 'Adv', 'Less Advance', 'Less Paid', 'Paid', 'आगाऊ'],
    likelyLocation: 'Financial table row 3 (44-50% height, 75-100% width)',
    extractionStrategy: 'Financial table row 3 targeted crop',
    ocrEnginePreference: 'firered',
    validationStrategy: 'Monetary numeric decimal format',
    normalizationStrategy: 'Clean numeric string to float',
    confidenceStrategy: 'Proximity to ADVANCE / PAID row label',
  },
  // ── 17. Total 1 (Gross Total) (MONEY) ──
  {
    key: 'total_1',
    label: 'Total 1 (Gross Total)',
    category: 'financials',
    semanticType: 'MONEY',
    dataType: 'number',
    extractionType: 'amount',
    description: 'Subtotal before tax deduction (Bill 1 + Bill 2 - Adv)',
    excelColumn: 'Total 1',
    excelWidth: 16,
    format: 'currency',
    likelyLabels: ['Total 1', 'Total', 'Sub Total', 'Gross Total', 'एकूण'],
    likelyLocation: 'Financial table row 4 (50-55% height, 75-100% width)',
    extractionStrategy: 'Financial table row 4 subtotal extractor',
    ocrEnginePreference: 'firered',
    validationStrategy: 'Arithmetic check: Total 1 = Bill 1 + Bill 2 - Advance',
    normalizationStrategy: 'Clean numeric string to float',
    confidenceStrategy: 'Arithmetic consistency bonus when sum matches',
  },
  // ── 18. TDS % (PERCENTAGE) ──
  {
    key: 'tds_percentage',
    label: 'TDS %',
    category: 'tax',
    semanticType: 'PERCENTAGE',
    dataType: 'number',
    extractionType: 'percentage',
    description: 'TDS tax rate percentage (e.g. 1%, 2%, 10%)',
    excelColumn: 'TDS %',
    excelWidth: 12,
    format: 'percentage',
    likelyLabels: ['TDS %', 'TDS', 'Less TDS', 'TDS Rate', '%'],
    likelyLocation: 'Financial table tax row (55-61% height, 65-78% width)',
    extractionStrategy: 'Tax percentage cell extractor',
    ocrEnginePreference: 'firered',
    validationStrategy: 'Valid tax rate (0% to 30%)',
    normalizationStrategy: 'Strip percentage symbol, parse numeric float',
    confidenceStrategy: 'Proximity to TDS row label',
  },
  // ── 19. TDS Amount (MONEY) ──
  {
    key: 'tds_amount',
    label: 'TDS Amount',
    category: 'tax',
    semanticType: 'MONEY',
    dataType: 'number',
    extractionType: 'amount',
    description: 'Calculated or specified TDS deduction amount',
    excelColumn: 'TDS Amount',
    excelWidth: 16,
    format: 'currency',
    likelyLabels: ['TDS Amount', 'TDS', 'Less TDS Amount', 'टीडीएस'],
    likelyLocation: 'Financial table tax row amount cell (55-61% height, 78-100% width)',
    extractionStrategy: 'Financial table tax amount cell targeted crop',
    ocrEnginePreference: 'firered',
    validationStrategy: 'Arithmetic check: TDS Amount = Total 1 * (TDS % / 100)',
    normalizationStrategy: 'Clean numeric string to float',
    confidenceStrategy: 'Percentage-to-amount consistency',
  },
  // ── 20. Total 2 (Net After TDS) (MONEY) ──
  {
    key: 'total_2',
    label: 'Total 2 (Net After TDS)',
    category: 'financials',
    semanticType: 'MONEY',
    dataType: 'number',
    extractionType: 'amount',
    description: 'Subtotal after deducting TDS (Total 1 - TDS Amount)',
    excelColumn: 'Total 2',
    excelWidth: 16,
    format: 'currency',
    likelyLabels: ['Total 2', 'Total', 'Net After TDS', 'एकूण २'],
    likelyLocation: 'Financial table row 6 (61-67% height, 75-100% width)',
    extractionStrategy: 'Financial table row 6 subtotal extractor',
    ocrEnginePreference: 'firered',
    validationStrategy: 'Arithmetic check: Total 2 = Total 1 - TDS Amount',
    normalizationStrategy: 'Clean numeric string to float',
    confidenceStrategy: 'Arithmetic consistency bonus when sum matches',
  },
  // ── 21. CGST % (PERCENTAGE) ──
  {
    key: 'cgst_percentage',
    label: 'CGST %',
    category: 'tax',
    semanticType: 'PERCENTAGE',
    dataType: 'number',
    extractionType: 'percentage',
    description: 'Central GST rate percentage (e.g. 2.5%, 6%, 9%, 14%)',
    excelColumn: 'CGST %',
    excelWidth: 12,
    format: 'percentage',
    likelyLabels: ['CGST %', 'CGST', 'Add CGST', '%'],
    likelyLocation: 'Financial table GST row 1 percentage cell (67-72% height, 65-78% width)',
    extractionStrategy: 'GST percentage cell extractor',
    ocrEnginePreference: 'firered',
    validationStrategy: 'Standard GST tax rate (0%, 2.5%, 6%, 9%, 14%, 18%)',
    normalizationStrategy: 'Strip percentage symbol, parse numeric float',
    confidenceStrategy: 'Proximity to CGST label',
  },
  // ── 22. CGST Amount (MONEY) ──
  {
    key: 'cgst_amount',
    label: 'CGST Amount',
    category: 'tax',
    semanticType: 'MONEY',
    dataType: 'number',
    extractionType: 'amount',
    description: 'Central GST amount added',
    excelColumn: 'CGST Amount',
    excelWidth: 16,
    format: 'currency',
    likelyLabels: ['CGST Amount', 'CGST', 'Add CGST Amount'],
    likelyLocation: 'Financial table GST row 1 amount cell (67-72% height, 78-100% width)',
    extractionStrategy: 'Strict monetary parser with single-digit/border false positive rejection',
    ocrEnginePreference: 'firered',
    validationStrategy: 'Arithmetic check: CGST Amount = Total 2 * (CGST % / 100); rejects isolated noise',
    normalizationStrategy: 'Clean numeric string to float; reject single-character table artifacts',
    confidenceStrategy: 'Percentage-to-amount consistency',
  },
  // ── 23. SGST % (PERCENTAGE) ──
  {
    key: 'sgst_percentage',
    label: 'SGST %',
    category: 'tax',
    semanticType: 'PERCENTAGE',
    dataType: 'number',
    extractionType: 'percentage',
    description: 'State GST rate percentage (e.g. 2.5%, 6%, 9%, 14%)',
    excelColumn: 'SGST %',
    excelWidth: 12,
    format: 'percentage',
    likelyLabels: ['SGST %', 'SGST', 'Add SGST', '%'],
    likelyLocation: 'Financial table GST row 2 percentage cell (72-78% height, 65-78% width)',
    extractionStrategy: 'GST percentage cell extractor',
    ocrEnginePreference: 'firered',
    validationStrategy: 'Standard GST tax rate (0%, 2.5%, 6%, 9%, 14%, 18%)',
    normalizationStrategy: 'Strip percentage symbol, parse numeric float',
    confidenceStrategy: 'Proximity to SGST label',
  },
  // ── 24. SGST Amount (MONEY) ──
  {
    key: 'sgst_amount',
    label: 'SGST Amount',
    category: 'tax',
    semanticType: 'MONEY',
    dataType: 'number',
    extractionType: 'amount',
    description: 'State GST amount added',
    excelColumn: 'SGST Amount',
    excelWidth: 16,
    format: 'currency',
    likelyLabels: ['SGST Amount', 'SGST', 'Add SGST Amount'],
    likelyLocation: 'Financial table GST row 2 amount cell (72-78% height, 78-100% width)',
    extractionStrategy: 'Strict monetary parser with single-digit/border false positive rejection',
    ocrEnginePreference: 'firered',
    validationStrategy: 'Arithmetic check: SGST Amount = Total 2 * (SGST % / 100)',
    normalizationStrategy: 'Clean numeric string to float; reject single-character table artifacts',
    confidenceStrategy: 'Percentage-to-amount consistency',
  },
  // ── 25. Round Off (+/-) (MONEY) ──
  {
    key: 'round_off',
    label: 'Round Off (+/-)',
    category: 'financials',
    semanticType: 'MONEY',
    dataType: 'number',
    extractionType: 'signed_amount',
    description: 'Fractional rounding adjustment (+/- paise)',
    excelColumn: 'Round Off',
    excelWidth: 14,
    format: 'currency',
    likelyLabels: ['Round Off', 'Rounding', 'Round Off (+/-)', 'Round', 'फरक'],
    likelyLocation: 'Financial table row 9 (78-84% height, 75-100% width)',
    extractionStrategy: 'Signed decimal parser (-0.99 to +0.99 or small integer adjustment)',
    ocrEnginePreference: 'firered',
    validationStrategy: 'Signed numeric value; returns null on "/" or blank without fabricating 0',
    normalizationStrategy: 'Parse optional +/- signs and decimals',
    confidenceStrategy: 'Small fractional check against Net Paid diff',
  },
  // ── 26. Net Paid Amount (MONEY) ──
  {
    key: 'net_paid',
    label: 'Net Paid Amount',
    category: 'net',
    semanticType: 'MONEY',
    dataType: 'number',
    extractionType: 'amount',
    required: true,
    description: 'Final net payable amount after tax, GST, and adjustments',
    excelColumn: 'Net Paid',
    excelWidth: 18,
    format: 'currency',
    likelyLabels: ['Net Paid Amount', 'Net Paid', 'Net Amount', 'Net Payable', 'Total Paid', 'Final Amount', 'एकूण दिलेली रक्कम'],
    likelyLocation: 'Bottom-right highlighted net box (84-90% height, 75-100% width)',
    extractionStrategy: 'High-resolution targeted net box crop + spatial consensus',
    ocrEnginePreference: 'consensus',
    validationStrategy: 'Mandatory monetary numeric decimal; Net Paid = Total 2 + CGST + SGST + Round Off',
    normalizationStrategy: 'Strict numeric parsing with disambiguation',
    confidenceStrategy: 'Arithmetic validation agreement and words cross-check',
  },
];


/** Creates an empty ExtractedVoucherFields object with default confidence & validity */
export function createEmptyVoucherFields(): ExtractedVoucherFields {
  const fields: Partial<ExtractedVoucherFields> = {};
  for (const field of HENU_VOUCHER_FIELDS) {
    (fields as any)[field.key] = {
      rawValue: '',
      normalizedValue: field.dataType === 'number' ? null : '',
      confidence: 0,
      validationStatus: 'valid',
    };
  }
  return fields as ExtractedVoucherFields;
}

/** Extracts pure business object from ExtractedVoucherFields */
export function extractCanonicalData(fields: ExtractedVoucherFields): HenuVoucherData {
  const data: Partial<HenuVoucherData> = {};
  for (const field of HENU_VOUCHER_FIELDS) {
    (data as any)[field.key] = fields[field.key]?.normalizedValue ?? (field.dataType === 'number' ? null : '');
  }
  return data as HenuVoucherData;
}
