/**
 * HENU CHECK OCR — CANONICAL FIELD SCHEMA
 * Module: Henu Check OCR
 */

import { CheckFieldMetadata, ExtractedCheckFields } from './types';

export const HENU_CHECK_FIELDS: CheckFieldMetadata[] = [
  {
    key: 'bank',
    label: 'Bank:',
    category: 'header',
    semanticType: 'TEXT',
    dataType: 'string',
    extractionType: 'name',
    required: true,
    description: 'Issuing bank name from cheque header/logo (e.g. Indian Bank, State Bank of India)',
    excelColumn: 'Bank',
    excelWidth: 26,
    format: 'text',
    likelyLabels: ['Bank', 'Bank Name', 'Branch'],
    likelyLocation: 'top-left or top-center',
  },
  {
    key: 'address',
    label: 'Address:',
    category: 'header',
    semanticType: 'TEXT',
    dataType: 'string',
    extractionType: 'address',
    required: false,
    description: 'Bank branch address / location information printed on the cheque',
    excelColumn: 'Address / Branch',
    excelWidth: 32,
    format: 'text',
    likelyLabels: ['Branch', 'Address', 'IFSC', 'Road', 'Street'],
    likelyLocation: 'top header area below bank name',
  },
  {
    key: 'date',
    label: 'Date (DDMMYYYY):',
    category: 'header',
    semanticType: 'DATE',
    dataType: 'date',
    extractionType: 'date',
    required: true,
    description: 'Cheque issue date printed/written in the date boxes in DDMMYYYY or DD/MM/YYYY format',
    excelColumn: 'Date (DDMMYYYY)',
    excelWidth: 18,
    format: 'date',
    likelyLabels: ['Date', 'D D M M Y Y Y Y', 'DDMMYYYY'],
    likelyLocation: 'top-right date box',
  },
  {
    key: 'payee_name',
    label: 'Pay / Payee Name:',
    category: 'parties',
    semanticType: 'TEXT',
    dataType: 'string',
    extractionType: 'name',
    required: true,
    description: 'Name of the payee / recipient printed/written after the "PAY" line',
    excelColumn: 'Pay / Payee Name',
    excelWidth: 30,
    format: 'text',
    likelyLabels: ['Pay', 'Payee', 'Pay To', 'Or Bearer'],
    likelyLocation: 'middle upper line',
  },
  {
    key: 'rupees_in_words',
    label: 'Rupees in Words:',
    category: 'financials',
    semanticType: 'MONEY',
    dataType: 'string',
    extractionType: 'words',
    required: true,
    description: 'Complete monetary amount written in words without truncation (e.g. Rupees One Lakh Only)',
    excelColumn: 'Rupees in Words',
    excelWidth: 36,
    format: 'text',
    likelyLabels: ['Rupees', 'Rupees in words', 'Amount in words', 'Only'],
    likelyLocation: 'middle line below payee',
  },
  {
    key: 'amount_in_figure',
    label: 'Amount in Figure: ₹',
    category: 'financials',
    semanticType: 'MONEY',
    dataType: 'number',
    extractionType: 'amount',
    required: true,
    description: 'Numeric cheque amount from the "₹" box (normalized to decimal number, e.g. 100000.00)',
    excelColumn: 'Amount in Figure (₹)',
    excelWidth: 20,
    format: 'currency',
    likelyLabels: ['₹', 'Rs', 'Amount', 'Rs.'],
    likelyLocation: 'middle-right amount box',
  },
  {
    key: 'account_no',
    label: 'A/c No.:',
    category: 'banking_identifiers',
    semanticType: 'IDENTIFIER',
    dataType: 'string',
    extractionType: 'reference_number',
    required: true,
    description: 'Bank account number printed/written on the cheque (preserves leading zeros)',
    excelColumn: 'A/c No.',
    excelWidth: 22,
    format: 'text',
    likelyLabels: ['A/c No.', 'Account No', 'A/c Number', 'Current A/c', 'SB A/c'],
    likelyLocation: 'middle-left account band',
  },
  {
    key: 'cheque_no',
    label: 'Cheque No:',
    category: 'banking_identifiers',
    semanticType: 'IDENTIFIER',
    dataType: 'string',
    extractionType: 'reference_number',
    required: true,
    description: 'Cheque number string (preserving leading zeros, e.g. 004582)',
    excelColumn: 'Cheque No',
    excelWidth: 18,
    format: 'text',
    likelyLabels: ['Cheque No', 'Chq No', 'Cheque Number', 'No.'],
    likelyLocation: 'bottom MICR band first block / top right corner',
  },
  {
    key: 'micr_code',
    label: 'MICR Code at bottom:',
    category: 'banking_identifiers',
    semanticType: 'IDENTIFIER',
    dataType: 'string',
    extractionType: 'micr',
    required: false,
    description: '22-digit or standardized bottom band MICR encoding',
    excelColumn: 'MICR Code',
    excelWidth: 28,
    format: 'text',
    likelyLabels: ['MICR', 'MICR Code', 'Bottom Band'],
    likelyLocation: 'bottom 1/2 inch of cheque',
  },
  {
    key: 'signature_by',
    label: 'Signature By:',
    category: 'signature',
    semanticType: 'TEXT',
    dataType: 'string',
    extractionType: 'signature',
    required: false,
    description: 'Printed signatory name or title if present; null if handwritten unreadable (zero hallucination)',
    excelColumn: 'Signature By',
    excelWidth: 24,
    format: 'text',
    likelyLabels: ['Authorised Signatory', 'Signatory', 'Signature', 'Please sign above this line'],
    likelyLocation: 'bottom-right signature area',
  },
];

export function createEmptyCheckFields(): ExtractedCheckFields {
  const fields: any = {};
  for (const meta of HENU_CHECK_FIELDS) {
    fields[meta.key] = {
      rawValue: '',
      normalizedValue: meta.dataType === 'number' ? null : null,
      confidence: 0,
      validationStatus: 'warning',
      status: 'MISSING',
    };
  }
  return fields as ExtractedCheckFields;
}
