/**
 * HENU VOUCHER OCR — STANDARD VOUCHER TEMPLATE PROFILE
 * Module: Henu Voucher OCR
 * 
 * Precise calibrated geometry matching canonical HENU OS Payment Voucher layout:
 * - Header Section: 0% to 18%
 * - Pay To / Charge To: 18% to 28%
 * - Particulars & Cheque Section (Left): 28% to 90%
 * - Financial Calculation Table (Right): 28% to 90%
 * - Signatures Section: > 90%
 */

import { VoucherTemplateDefinition } from './types';

export const STANDARD_VOUCHER_TEMPLATE: VoucherTemplateDefinition = {
  id: 'standard-society-voucher',
  name: 'Standard Society Payment Voucher (2-per-page A4)',
  description: 'Canonical dual-voucher layout with Society Header, Pay/Charge To, Particulars, Financial Table, and Signatures.',
  aspectRatio: 1.32,
  headerAnchors: [
    'CO-OPERATIVE HOUSING SOCIETY',
    'CO. OP. HSG. SOC',
    'VOUCHER',
    'PAY TO',
    'CHARGE TO',
    'PARTICULARS',
    'NET PAID',
    'रक्कम',
    'पावती',
  ],
  fieldZones: [
    // ── 1. Header Section (Top 0% to 18%) ──
    {
      fieldKey: 'society_name',
      label: 'Society Name',
      zone: { xMin: 0.02, yMin: 0.01, xMax: 0.70, yMax: 0.08 },
      anchorKeywords: ['SOCIETY', 'HOUSING', 'HEIGHTS', 'CHS', 'CO-OP', 'मर्यादित', 'सोसायटी'],
      expectedType: 'string',
      extractionType: 'name',
      psm: '6',
      priority: 10,
    },
    {
      fieldKey: 'registration_no',
      label: 'Registration Number',
      zone: { xMin: 0.02, yMin: 0.075, xMax: 0.70, yMax: 0.125 },
      anchorKeywords: ['REG. NO.', 'REG NO', 'REGN NO', 'REGISTRATION NO', 'REGN', 'YEAR', 'नोंदणी'],
      expectedType: 'string',
      extractionType: 'mixed_alphanumeric',
      psm: '7',
      priority: 9,
    },
    {
      fieldKey: 'society_address',
      label: 'Society Address',
      zone: { xMin: 0.02, yMin: 0.12, xMax: 0.70, yMax: 0.178 },
      anchorKeywords: ['ROAD', 'NAGAR', 'MARG', 'MUMBAI', 'PUNE', 'THANE', 'STREET', 'CTS', 'रस्ता'],
      expectedType: 'string',
      extractionType: 'address',
      psm: '6',
      priority: 8,
    },
    {
      fieldKey: 'voucher_no',
      label: 'Voucher Number',
      zone: { xMin: 0.72, yMin: 0.015, xMax: 0.98, yMax: 0.09 },
      anchorKeywords: ['VOUCHER NO', 'VCH NO', 'VR NO', 'NO.', 'क्रमांक'],
      expectedType: 'string',
      extractionType: 'reference_number',
      regexPatterns: [/VOUCHER\s*(?:NO|NUMBER)?[\s\.\:\#]*([A-Z0-9\-\/]+)/i, /VR\s*(?:NO)?[\s\.\:\#]*([A-Z0-9\-\/]+)/i],
      psm: '7',
      charWhitelist: '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ-/#०१२३४५६७८९',
      priority: 10,
    },
    {
      fieldKey: 'voucher_date',
      label: 'Voucher Date',
      zone: { xMin: 0.72, yMin: 0.09, xMax: 0.98, yMax: 0.175 },
      anchorKeywords: ['DATE', 'DT', 'दिनांक'],
      expectedType: 'date',
      extractionType: 'date',
      regexPatterns: [/(?:DATE|DT)[\s\.\:\#]*(\d{1,2}[\/\-\.\s]\d{1,2}[\/\-\.\s]\d{2,4})/i],
      psm: '7',
      charWhitelist: '0123456789/-.Date:DTदिनांक०१२३४५६७८९ ',
      priority: 10,
    },

    // ── 2. Pay / Charge To Section (18% to 28%) ──
    {
      fieldKey: 'pay_to',
      label: 'Pay To (Payee)',
      zone: { xMin: 0.11, yMin: 0.185, xMax: 0.56, yMax: 0.278 },
      anchorKeywords: ['PAY TO', 'PAID TO', 'M/S', 'MR', 'MRS', 'श्री', 'नाव'],
      expectedType: 'string',
      extractionType: 'name',
      psm: '7',
      suppressRulingLines: true,
      priority: 9,
    },
    {
      fieldKey: 'charge_to',
      label: 'Charge To (Ledger Head)',
      zone: { xMin: 0.70, yMin: 0.185, xMax: 0.98, yMax: 0.278 },
      anchorKeywords: ['CHARGE TO', 'DEBIT TO', 'ACCOUNT', 'A/C', 'खर्च'],
      expectedType: 'string',
      extractionType: 'ledger_text',
      psm: '7',
      suppressRulingLines: true,
      priority: 9,
    },

    // ── 3. Particulars & Cheque Section (28% to 90% - Left Column) ──
    {
      fieldKey: 'particulars',
      label: 'Particulars / Narration',
      zone: { xMin: 0.02, yMin: 0.325, xMax: 0.56, yMax: 0.595 },
      anchorKeywords: ['PARTICULARS', 'BEING', 'NARRATION', 'तपशील', 'बद्दल'],
      expectedType: 'string',
      extractionType: 'sentence',
      psm: '6',
      suppressRulingLines: true,
      priority: 8,
    },
    {
      fieldKey: 'bill_no',
      label: 'Bill Number',
      zone: { xMin: 0.13, yMin: 0.595, xMax: 0.56, yMax: 0.655 },
      anchorKeywords: ['BILL NO', 'INVOICE NO', 'INV NO', 'बिल नं'],
      expectedType: 'string',
      extractionType: 'reference_number',
      psm: '7',
      charWhitelist: '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ-/#०१२३४५६७८९',
      priority: 8,
    },
    {
      fieldKey: 'bank_name',
      label: 'Bank Name',
      zone: { xMin: 0.19, yMin: 0.655, xMax: 0.56, yMax: 0.715 },
      anchorKeywords: ['BANK', 'BANK NAME', 'HDFC', 'SBI', 'ICICI', 'AXIS', 'SARASWAT', 'बँक'],
      expectedType: 'string',
      extractionType: 'name',
      psm: '7',
      suppressRulingLines: true,
      priority: 8,
    },
    {
      fieldKey: 'cheque_no',
      label: 'Cheque Number',
      zone: { xMin: 0.17, yMin: 0.715, xMax: 0.39, yMax: 0.775 },
      anchorKeywords: ['CHEQUE NO', 'CHQ NO', 'UTR', 'NEFT', 'चेक नं'],
      expectedType: 'string',
      extractionType: 'reference_number',
      psm: '7',
      charWhitelist: '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ-/#०१२३४५६७८९',
      priority: 8,
    },
    {
      fieldKey: 'cheque_date',
      label: 'Cheque Date',
      zone: { xMin: 0.43, yMin: 0.715, xMax: 0.56, yMax: 0.775 },
      anchorKeywords: ['DATE', 'DT', 'दिनांक'],
      expectedType: 'date',
      extractionType: 'date',
      regexPatterns: [/(?:DATE|DT)[\s\.\:\#]*(\d{1,2}[\/\-\.\s]\d{1,2}[\/\-\.\s]\d{2,4})/i],
      psm: '7',
      charWhitelist: '0123456789/-.Date:DTदिनांक०१२३४५६७८९ ',
      priority: 7,
    },
    {
      fieldKey: 'rupees',
      label: 'Rupees (Words or Net Rs.)',
      zone: { xMin: 0.06, yMin: 0.775, xMax: 0.56, yMax: 0.835 },
      anchorKeywords: ['RS.', 'RUPEES', '₹', 'रुपये'],
      expectedType: 'string',
      extractionType: 'words',
      psm: '7',
      priority: 8,
    },

    // ── 4. Financial Calculation Table (28% to 90% - Right Column) ──
    {
      fieldKey: 'bill_amount_1',
      label: 'Bill Amount 1',
      zone: { xMin: 0.77, yMin: 0.325, xMax: 0.98, yMax: 0.382 },
      anchorKeywords: ['BILL AMOUNT 1', 'BILL AMOUNT (1)', 'BILL AMOUNT', 'BILL AMT 1', 'BILL AMT', 'GROSS'],
      expectedType: 'number',
      extractionType: 'amount',
      psm: '8',
      isNumericOnly: true,
      priority: 8,
    },
    {
      fieldKey: 'bill_amount_2',
      label: 'Bill Amount 2',
      zone: { xMin: 0.77, yMin: 0.382, xMax: 0.98, yMax: 0.439 },
      anchorKeywords: ['BILL AMOUNT 2', 'BILL AMOUNT (2)', 'BILL AMT 2', 'EXTRA'],
      expectedType: 'number',
      extractionType: 'amount',
      psm: '8',
      isNumericOnly: true,
      priority: 6,
    },
    {
      fieldKey: 'advance_paid',
      label: 'Advance / Paid',
      zone: { xMin: 0.77, yMin: 0.439, xMax: 0.98, yMax: 0.496 },
      anchorKeywords: ['ADVANCE PAID', 'LESS ADVANCE', 'LESS PAID', 'ADVANCE', 'ADV', 'FINE', 'ADD FINE', 'LESS FINE', 'DEDUCTION', 'आगाऊ'],
      expectedType: 'number',
      extractionType: 'amount',
      psm: '8',
      isNumericOnly: true,
      priority: 8,
    },
    {
      fieldKey: 'total_1',
      label: 'Total 1',
      zone: { xMin: 0.77, yMin: 0.496, xMax: 0.98, yMax: 0.553 },
      anchorKeywords: ['TOTAL 1', 'GROSS TOTAL', 'TOTAL (1)', 'SUB TOTAL', 'TOTAL', 'एकूण १', 'एकूण'],
      expectedType: 'number',
      extractionType: 'amount',
      psm: '8',
      isNumericOnly: true,
      priority: 8,
    },
    {
      fieldKey: 'tds_percentage',
      label: 'TDS %',
      zone: { xMin: 0.66, yMin: 0.553, xMax: 0.77, yMax: 0.610 },
      anchorKeywords: ['TDS %', 'LESS TDS @', 'LESS TDS', 'TDS @', 'TDS', '%'],
      expectedType: 'number',
      extractionType: 'percentage',
      psm: '8',
      isNumericOnly: true,
      priority: 7,
    },
    {
      fieldKey: 'tds_amount',
      label: 'TDS Amount',
      zone: { xMin: 0.77, yMin: 0.553, xMax: 0.98, yMax: 0.610 },
      anchorKeywords: ['TDS AMOUNT', 'LESS TDS AMOUNT', 'TDS @', 'LESS TDS', 'TDS', 'टीडीएस'],
      expectedType: 'number',
      extractionType: 'amount',
      psm: '8',
      isNumericOnly: true,
      priority: 8,
    },
    {
      fieldKey: 'total_2',
      label: 'Total 2',
      zone: { xMin: 0.77, yMin: 0.610, xMax: 0.98, yMax: 0.667 },
      anchorKeywords: ['TOTAL 2', 'NET AFTER TDS', 'TOTAL (2)', 'SUB TOTAL 2', 'एकूण २'],
      expectedType: 'number',
      extractionType: 'amount',
      psm: '8',
      isNumericOnly: true,
      priority: 8,
    },
    {
      fieldKey: 'cgst_percentage',
      label: 'CGST %',
      zone: { xMin: 0.66, yMin: 0.667, xMax: 0.77, yMax: 0.724 },
      anchorKeywords: ['CGST %', 'ADD CGST @', 'CGST @', 'ADD CGST', 'CGST', '%'],
      expectedType: 'number',
      extractionType: 'percentage',
      psm: '8',
      isNumericOnly: true,
      priority: 7,
    },
    {
      fieldKey: 'cgst_amount',
      label: 'CGST Amount',
      zone: { xMin: 0.77, yMin: 0.667, xMax: 0.98, yMax: 0.724 },
      anchorKeywords: ['CGST AMOUNT', 'ADD CGST AMOUNT', 'CGST @', 'ADD CGST', 'CGST'],
      expectedType: 'number',
      extractionType: 'amount',
      psm: '8',
      isNumericOnly: true,
      priority: 8,
    },
    {
      fieldKey: 'sgst_percentage',
      label: 'SGST %',
      zone: { xMin: 0.66, yMin: 0.724, xMax: 0.77, yMax: 0.781 },
      anchorKeywords: ['SGST %', 'ADD SGST @', 'SGST @', 'ADD SGST', 'SGST', '%'],
      expectedType: 'number',
      extractionType: 'percentage',
      psm: '8',
      isNumericOnly: true,
      priority: 7,
    },
    {
      fieldKey: 'sgst_amount',
      label: 'SGST Amount',
      zone: { xMin: 0.77, yMin: 0.724, xMax: 0.98, yMax: 0.781 },
      anchorKeywords: ['SGST AMOUNT', 'ADD SGST AMOUNT', 'SGST @', 'ADD SGST', 'SGST'],
      expectedType: 'number',
      extractionType: 'amount',
      psm: '8',
      isNumericOnly: true,
      priority: 8,
    },
    {
      fieldKey: 'round_off',
      label: 'Round Off (+/-)',
      zone: { xMin: 0.77, yMin: 0.781, xMax: 0.98, yMax: 0.838 },
      anchorKeywords: ['ROUND OFF', 'ROUND'],
      expectedType: 'number',
      extractionType: 'signed_amount',
      psm: '8',
      isNumericOnly: true,
      priority: 7,
    },
    {
      fieldKey: 'net_paid',
      label: 'Net Paid Amount',
      zone: { xMin: 0.77, yMin: 0.838, xMax: 0.98, yMax: 0.898 },
      anchorKeywords: ['NET PAID', 'NET AMOUNT', 'FINAL AMOUNT', 'एकूण दिलेली रक्कम'],
      expectedType: 'number',
      extractionType: 'amount',
      psm: '8',
      isNumericOnly: true,
      priority: 10,
    },
  ],
};
